# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('flysafe', ['network', 'internet', 'ascon-128'])

    module.use.append('OPENSSL')
    module.use.append('ascon-lib')

    module.source = [
        'model/flysafe-tag.cc',
        'model/flysafe-statistics.cc',
#        'model/status-on.cc',
        'model/flysafe-onoff.cc',
        'model/flysafe-packet-sink.cc',
        'helper/utils.cc',
        ]

    module_test = bld.create_ns3_module_test_library('flysafe')
    module_test.source = [
        'test/flysafe-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'flysafe'
    headers.source = [
        'model/flysafe-tag.h',
        'model/flysafe-statistics.h',
#        'model/status-on.h',
        'model/flysafe-onoff.h',
        'model/flysafe-packet-sink.h',
        'helper/utils.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()
