# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    ascon_lib = bld(features='c cstlib',
                    target='ascon-lib',
                    source=['aead.c', 'printstate.c'])
    ascon_lib.includes = '.'

    module = bld.create_ns3_module('ascon-128', [])
    module.use.append('ascon-lib')

    headers = bld(features='ns3header')
    headers.module = 'ascon-128'
    headers.source = [
        'crypto_aead.h',
        'api.h',
        'ascon.h',
        'constants.h',
        'permutations.h',
        'printstate.h',
        'round.h',
        'word.h',
    ]
